spring:
  datasource:
    username: username
    password: password
  mail:
    email: example@gmail.com
    host: smtp.gmail.hu
    port: 587
    username: gmail
    password: password
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true